export const candidates = [
  {
    id: 1,
    firstName: "Valeriu",
    lastName: "Rusu",
    email: "valeriu.rusu111@gmail.com",
    position: "Software Engineer",
    completed: true,
    score: 100,
    time: "01:33:02",
    favorite: true,
  },
  {
    id: 2,
    firstName: "David",
    lastName: "Le",
    email: "david.le@gmail.com",
    position: "Software Engineer",
    completed: true,
    score: 93,
    time: "01:44:01",
    favorite: false,
  },
  {
    id: 3,
    firstName: "Karsten",
    lastName: "Dehler",
    email: "karsten.dehler37@gmail.com",
    position: "Project Manager",
    completed: false,
    score: null,
    time: null,
    favorite: false,
  },
  {
    id: 4,
    firstName: "Nadejda",
    lastName: "Didenco",
    email: "nadea.didenco@gmail.com",
    position: "Marketing Manager",
    completed: false,
    score: null,
    time: null,
    favorite: false,
  },
  {
    id: 5,
    firstName: "Viktoria",
    lastName: "Kouni",
    email: "viktoria.kouni@gmail.com",
    position: "Project Manager",
    completed: true,
    score: 78,
    time: "02:19:11",
    favorite: false,
  },
  {
    id: 6,
    firstName: "Raluca",
    lastName: "Petrovici",
    email: "raluca.petrovici@gmail.com",
    position: "Software Engineer",
    completed: true,
    score: 57,
    time: "00:59:13",
    favorite: false,
  },
  {
    id: 7,
    firstName: "Valeriu",
    lastName: "Marandici",
    email: "valeriu.marandici99@gmail.com",
    position: "Software Engineer",
    completed: true,
    score: 22,
    time: "02:33:17",
    favorite: false,
  },
  {
    id: 8,
    firstName: "Krystian",
    lastName: "Goluch",
    email: "naghibator98@gmail.com",
    position: "Software Engineer",
    completed: true,
    score: 100,
    time: "01:37:52",
    favorite: true,
  },
  {
    id: 9,
    firstName: "Luis",
    lastName: "Figo",
    email: "luis.figo@gmail.com",
    position: "Software Engineer",
    completed: true,
    score: 55,
    time: "01:33:17",
    favorite: false,
  },
  {
    id: 10,
    firstName: "Cristiano",
    lastName: "Ronaldo",
    email: "cristiano.ronaldo7@gmail.com",
    position: "Solution Architect",
    completed: true,
    score: 100,
    time: "00:33:17",
    favorite: true,
  },
  {
    id: 11,
    firstName: "David",
    lastName: "De Gea",
    email: "david.degea1@gmail.com",
    position: "Solution Consultant",
    completed: false,
    score: null,
    time: null,
    favorite: false,
  },
  {
    id: 12,
    firstName: "Edwin",
    lastName: "Van der Sar",
    email: "flying.dutchman@gmail.com",
    position: "Professional Services Project Manager",
    completed: true,
    score: 73,
    time: "02:11:12",
    favorite: false,
  },
];
