export const chartData = [
  {
    name: "January",
    candidates: 55,
    completed: 49,
    pending: 6,
    perfectScore: 11,
    favorites: 3,
  },
  {
    name: "February",
    candidates: 22,
    completed: 11,
    pending: 11,
    perfectScore: 3,
    favorites: 3,
  },
  {
    name: "March",
    candidates: 32,
    completed: 31,
    pending: 2,
    perfectScore: 9,
    favorites: 6,
  },
  {
    name: "April",
    candidates: 111,
    completed: 102,
    pending: 9,
    perfectScore: 24,
    favorites: 11,
  },
  {
    name: "May",
    candidates: 43,
    completed: 37,
    pending: 6,
    perfectScore: 1,
    favorites: 5,
  },
  {
    name: "June",
    candidates: 35,
    completed: 32,
    pending: 3,
    perfectScore: 21,
    favorites: 20,
  },
  {
    name: "July",
    candidates: 34,
    completed: 22,
    pending: 12,
    perfectScore: 7,
    favorites: 7,
  },
  {
    name: "August",
    candidates: 12,
    completed: 7,
    pending: 5,
    perfectScore: 1,
    favorites: 0,
  },
  {
    name: "September",
    candidates: 66,
    completed: 56,
    pending: 10,
    perfectScore: 17,
    favorites: 13,
  },
  {
    name: "October",
    candidates: 78,
    completed: 71,
    pending: 7,
    perfectScore: 26,
    favorites: 17,
  },
  {
    name: "November",
    candidates: 11,
    completed: 11,
    pending: 0,
    perfectScore: 5,
    favorites: 3,
  },
  {
    name: "December",
    candidates: 12,
    completed: 9,
    pending: 3,
    perfectScore: 4,
    favorites: 3,
  },
];
