export const positions = [
  {
    id: "JR575",
    name: "Solution Architect",
    location: "Sydney, Australia",
    type: "Full Time",
    posted: "5 Days Ago",
  },
  {
    id: "JR553",
    name: "Project Manager",
    location: "Sydney, Australia",
    type: "Full Time",
    posted: "5 Days Ago",
  },
  {
    id: "JR522",
    name: "R&D - Developer/Scrummaster",
    location: "Aarhus, Denmark",
    type: "Full Time",
    posted: "5 Days Ago",
  },
  {
    id: "JR546",
    name: "Solution Consultant",
    location: "Sydney, Australia",
    type: "Full Time",
    posted: "5 Days Ago",
  },
  {
    id: "JR462",
    name: "Professional Services Project Manager",
    location: "Atlanta, Georgia",
    type: "Full Time",
    posted: "9 Days Ago",
  },
  {
    id: "JR480",
    name: "Sales Support Consultant",
    location: "Reading, UK",
    type: "Full Time",
    posted: "9 Days Ago",
  },
  {
    id: "JR442",
    name: "Solution Consultant",
    location: "Bangalore, India",
    type: "Full Time",
    posted: "27 Days Ago",
  },
  {
    id: "JR460",
    name: "Senior Software Developer, R&D - Full Stack Java with ReactJS",
    location: "Bangalore, India",
    type: "Full Time",
    posted: "27 Days Ago",
  },
];
